/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahorcado;

import static ahorcado.Main.adminPalabrasSecretas;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jenniferbueso
 */
public class AhorcadosVisual extends javax.swing.JFrame {
    private JuegoAhorcadoFijo juegoAhorcadoFijo;
    private JuegoAhorcadoAzar juegoAhorcadoAzar;
    
    public AhorcadosVisual() {
        initComponents();
        
        Intento5.setVisible(false);
        Intento4.setVisible(false);
        Intento3.setVisible(false);
        Intento2.setVisible(false);
        Intento1.setVisible(false);
        Intento0.setVisible(false);
        
        if (Main.adminPalabrasSecretas.isModoFijo()) {
            iniciarJuegoFijo();
        }  else if (Main.adminPalabrasSecretas.isModoAzar()) {
            iniciarJuegoAzar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonesPanel = new javax.swing.JPanel();
        BotonA = new javax.swing.JButton();
        BotonB = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        BotonD = new javax.swing.JButton();
        BotonE = new javax.swing.JButton();
        BotonF = new javax.swing.JButton();
        BotonG = new javax.swing.JButton();
        BotonH = new javax.swing.JButton();
        BotonI = new javax.swing.JButton();
        BotonJ = new javax.swing.JButton();
        BotonK = new javax.swing.JButton();
        BotonL = new javax.swing.JButton();
        BotonN = new javax.swing.JButton();
        BotonÑ = new javax.swing.JButton();
        BotonO = new javax.swing.JButton();
        BotonQ = new javax.swing.JButton();
        BotonP = new javax.swing.JButton();
        BotonM = new javax.swing.JButton();
        BotonR = new javax.swing.JButton();
        BotonS = new javax.swing.JButton();
        BotonT = new javax.swing.JButton();
        BotonU = new javax.swing.JButton();
        BotonV = new javax.swing.JButton();
        BotonW = new javax.swing.JButton();
        BotonZ = new javax.swing.JButton();
        BotonY = new javax.swing.JButton();
        BotonX = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JLabel();
        PalabraOcultaLabel = new javax.swing.JLabel();
        IntentosLabel = new javax.swing.JLabel();
        Intento5 = new javax.swing.JLabel();
        Intento4 = new javax.swing.JLabel();
        Intento3 = new javax.swing.JLabel();
        Intento2 = new javax.swing.JLabel();
        Intento1 = new javax.swing.JLabel();
        Intento0 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonesPanel.setBackground(new java.awt.Color(255, 248, 240));

        BotonA.setBackground(new java.awt.Color(255, 255, 255));
        BotonA.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonA.setForeground(new java.awt.Color(0, 0, 0));
        BotonA.setText("A");
        BotonA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAMouseClicked(evt);
            }
        });

        BotonB.setBackground(new java.awt.Color(255, 255, 255));
        BotonB.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonB.setForeground(new java.awt.Color(0, 0, 0));
        BotonB.setText("B");
        BotonB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBMouseClicked(evt);
            }
        });

        BotonC.setBackground(new java.awt.Color(255, 255, 255));
        BotonC.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonC.setForeground(new java.awt.Color(0, 0, 0));
        BotonC.setText("C");
        BotonC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCMouseClicked(evt);
            }
        });

        BotonD.setBackground(new java.awt.Color(255, 255, 255));
        BotonD.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonD.setForeground(new java.awt.Color(0, 0, 0));
        BotonD.setText("D");
        BotonD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDMouseClicked(evt);
            }
        });

        BotonE.setBackground(new java.awt.Color(255, 255, 255));
        BotonE.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonE.setForeground(new java.awt.Color(0, 0, 0));
        BotonE.setText("E");
        BotonE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEMouseClicked(evt);
            }
        });

        BotonF.setBackground(new java.awt.Color(255, 255, 255));
        BotonF.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonF.setForeground(new java.awt.Color(0, 0, 0));
        BotonF.setText("F");
        BotonF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonFMouseClicked(evt);
            }
        });

        BotonG.setBackground(new java.awt.Color(255, 255, 255));
        BotonG.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonG.setForeground(new java.awt.Color(0, 0, 0));
        BotonG.setText("G");
        BotonG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGMouseClicked(evt);
            }
        });

        BotonH.setBackground(new java.awt.Color(255, 255, 255));
        BotonH.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonH.setForeground(new java.awt.Color(0, 0, 0));
        BotonH.setText("H");
        BotonH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHMouseClicked(evt);
            }
        });

        BotonI.setBackground(new java.awt.Color(255, 255, 255));
        BotonI.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonI.setForeground(new java.awt.Color(0, 0, 0));
        BotonI.setText("I");
        BotonI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIMouseClicked(evt);
            }
        });

        BotonJ.setBackground(new java.awt.Color(255, 255, 255));
        BotonJ.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonJ.setForeground(new java.awt.Color(0, 0, 0));
        BotonJ.setText("J");
        BotonJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonJMouseClicked(evt);
            }
        });

        BotonK.setBackground(new java.awt.Color(255, 255, 255));
        BotonK.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonK.setForeground(new java.awt.Color(0, 0, 0));
        BotonK.setText("K");
        BotonK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonKMouseClicked(evt);
            }
        });

        BotonL.setBackground(new java.awt.Color(255, 255, 255));
        BotonL.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonL.setForeground(new java.awt.Color(0, 0, 0));
        BotonL.setText("L");
        BotonL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLMouseClicked(evt);
            }
        });

        BotonN.setBackground(new java.awt.Color(255, 255, 255));
        BotonN.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonN.setForeground(new java.awt.Color(0, 0, 0));
        BotonN.setText("N");
        BotonN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonNMouseClicked(evt);
            }
        });

        BotonÑ.setBackground(new java.awt.Color(255, 255, 255));
        BotonÑ.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonÑ.setForeground(new java.awt.Color(0, 0, 0));
        BotonÑ.setText("Ñ");
        BotonÑ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonÑ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonÑMouseClicked(evt);
            }
        });

        BotonO.setBackground(new java.awt.Color(255, 255, 255));
        BotonO.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonO.setForeground(new java.awt.Color(0, 0, 0));
        BotonO.setText("O");
        BotonO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonOMouseClicked(evt);
            }
        });

        BotonQ.setBackground(new java.awt.Color(255, 255, 255));
        BotonQ.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonQ.setForeground(new java.awt.Color(0, 0, 0));
        BotonQ.setText("Q");
        BotonQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonQMouseClicked(evt);
            }
        });

        BotonP.setBackground(new java.awt.Color(255, 255, 255));
        BotonP.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonP.setForeground(new java.awt.Color(0, 0, 0));
        BotonP.setText("P");
        BotonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPMouseClicked(evt);
            }
        });

        BotonM.setBackground(new java.awt.Color(255, 255, 255));
        BotonM.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonM.setForeground(new java.awt.Color(0, 0, 0));
        BotonM.setText("M");
        BotonM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMMouseClicked(evt);
            }
        });

        BotonR.setBackground(new java.awt.Color(255, 255, 255));
        BotonR.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonR.setForeground(new java.awt.Color(0, 0, 0));
        BotonR.setText("R");
        BotonR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRMouseClicked(evt);
            }
        });

        BotonS.setBackground(new java.awt.Color(255, 255, 255));
        BotonS.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonS.setForeground(new java.awt.Color(0, 0, 0));
        BotonS.setText("S");
        BotonS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSMouseClicked(evt);
            }
        });

        BotonT.setBackground(new java.awt.Color(255, 255, 255));
        BotonT.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonT.setForeground(new java.awt.Color(0, 0, 0));
        BotonT.setText("T");
        BotonT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTMouseClicked(evt);
            }
        });

        BotonU.setBackground(new java.awt.Color(255, 255, 255));
        BotonU.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonU.setForeground(new java.awt.Color(0, 0, 0));
        BotonU.setText("U");
        BotonU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonUMouseClicked(evt);
            }
        });

        BotonV.setBackground(new java.awt.Color(255, 255, 255));
        BotonV.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonV.setForeground(new java.awt.Color(0, 0, 0));
        BotonV.setText("V");
        BotonV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVMouseClicked(evt);
            }
        });

        BotonW.setBackground(new java.awt.Color(255, 255, 255));
        BotonW.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonW.setForeground(new java.awt.Color(0, 0, 0));
        BotonW.setText("W");
        BotonW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonWMouseClicked(evt);
            }
        });

        BotonZ.setBackground(new java.awt.Color(255, 255, 255));
        BotonZ.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonZ.setForeground(new java.awt.Color(0, 0, 0));
        BotonZ.setText("Z");
        BotonZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonZMouseClicked(evt);
            }
        });

        BotonY.setBackground(new java.awt.Color(255, 255, 255));
        BotonY.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonY.setForeground(new java.awt.Color(0, 0, 0));
        BotonY.setText("Y");
        BotonY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonYMouseClicked(evt);
            }
        });

        BotonX.setBackground(new java.awt.Color(255, 255, 255));
        BotonX.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        BotonX.setForeground(new java.awt.Color(0, 0, 0));
        BotonX.setText("X");
        BotonX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonesPanelLayout = new javax.swing.GroupLayout(BotonesPanel);
        BotonesPanel.setLayout(BotonesPanelLayout);
        BotonesPanelLayout.setHorizontalGroup(
            BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonesPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonesPanelLayout.createSequentialGroup()
                            .addComponent(BotonR, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonS, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonU, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonW, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonesPanelLayout.createSequentialGroup()
                            .addComponent(BotonX, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonY, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(125, 125, 125)))
                    .addGroup(BotonesPanelLayout.createSequentialGroup()
                        .addComponent(BotonM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BotonesPanelLayout.createSequentialGroup()
                        .addComponent(BotonG, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonH, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonI, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BotonesPanelLayout.createSequentialGroup()
                        .addComponent(BotonA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonE, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonF, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        BotonesPanelLayout.setVerticalGroup(
            BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesPanelLayout.createSequentialGroup()
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonA)
                    .addComponent(BotonB)
                    .addComponent(BotonC)
                    .addComponent(BotonD)
                    .addComponent(BotonE)
                    .addComponent(BotonF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonG)
                    .addComponent(BotonH)
                    .addComponent(BotonI)
                    .addComponent(BotonJ)
                    .addComponent(BotonK)
                    .addComponent(BotonL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonM)
                    .addComponent(BotonN)
                    .addComponent(BotonÑ)
                    .addComponent(BotonO)
                    .addComponent(BotonP)
                    .addComponent(BotonQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonR)
                    .addComponent(BotonS)
                    .addComponent(BotonT)
                    .addComponent(BotonU)
                    .addComponent(BotonV)
                    .addComponent(BotonW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonX)
                    .addGroup(BotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonZ)
                        .addComponent(BotonY)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel1.add(BotonesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 399, 540, 220));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 60, 50));

        PalabraOcultaLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        PalabraOcultaLabel.setForeground(new java.awt.Color(0, 0, 0));
        PalabraOcultaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(PalabraOcultaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 321, 490, 40));

        IntentosLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        IntentosLabel.setForeground(new java.awt.Color(255, 255, 255));
        IntentosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntentosLabel.setText("1");
        jPanel1.add(IntentosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 84, 30, 30));

        Intento5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento5.png"))); // NOI18N
        jPanel1.add(Intento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 60, 270, 220));

        Intento4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento 4.png"))); // NOI18N
        jPanel1.add(Intento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 62, 270, 220));

        Intento3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento3.png"))); // NOI18N
        jPanel1.add(Intento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 270, 220));

        Intento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento2.png"))); // NOI18N
        jPanel1.add(Intento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 64, 270, 220));

        Intento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento1.png"))); // NOI18N
        jPanel1.add(Intento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 63, 270, 220));

        Intento0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Intento0.png"))); // NOI18N
        jPanel1.add(Intento0, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 63, 270, 220));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AhorcadosVisual.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 727, 682));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void iniciarJuegoFijo() {
        juegoAhorcadoFijo = new JuegoAhorcadoFijo(Main.adminPalabrasSecretas.getPalabraFija());
        actualizarInterfaz();
    }
    
    private void iniciarJuegoAzar() {
        juegoAhorcadoAzar = new JuegoAhorcadoAzar(adminPalabrasSecretas.getPalabras());
        actualizarInterfaz();
    }
    
    private void actualizarInterfaz() {
        if (juegoAhorcadoFijo != null) {
            PalabraOcultaLabel.setText(juegoAhorcadoFijo.getPalabraActual());
            IntentosLabel.setText(String.valueOf(juegoAhorcadoFijo.getIntentos()));
        } else if (juegoAhorcadoAzar != null) {
            PalabraOcultaLabel.setText(juegoAhorcadoAzar.getPalabraActual());
            IntentosLabel.setText(String.valueOf(juegoAhorcadoAzar.getIntentos()));
        }
    }
    
    private void jugar() {
        if (Main.adminPalabrasSecretas.isModoFijo() && !Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoFijo.jugar();
            PalabraOcultaLabel.setText(juegoAhorcadoFijo.getPalabraActual());
            IntentosLabel.setText(String.valueOf(juegoAhorcadoFijo.getIntentos()));
        } else if (Main.adminPalabrasSecretas.isModoAzar() && !Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoAzar.jugar();
            PalabraOcultaLabel.setText(juegoAhorcadoAzar.getPalabraActual());
            IntentosLabel.setText(String.valueOf(juegoAhorcadoAzar.getIntentos()));
        }
            
            if (juegoAhorcadoFijo != null && juegoAhorcadoFijo.isPartidaGanada()) {
                Main.adminPalabrasSecretas.setModoFijo(false);
                Main.adminPalabrasSecretas.setModoAzar(false);
                juegoAhorcadoFijo.setPartidaGanada(false);
                MenuPrincipal menuPrincipal = new MenuPrincipal();
                menuPrincipal.setVisible(true);
                this.setVisible(false);
            } else if (juegoAhorcadoAzar != null && juegoAhorcadoAzar.isPartidaGanada()) {
                Main.adminPalabrasSecretas.setModoFijo(false);
                Main.adminPalabrasSecretas.setModoAzar(false);
                juegoAhorcadoAzar.setPartidaGanada(false);
                MenuPrincipal menuPrincipal = new MenuPrincipal();
                menuPrincipal.setVisible(true);
                this.setVisible(false);
            }
            
            actualizarIntentos();
        
    }
    
    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro(a) que desea regresar al Menú Principal?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            ModoJuego modoJuego = new ModoJuego();
            modoJuego.setVisible(true);
            this.setVisible(false);
        }
       
    }//GEN-LAST:event_BotonRegresarMouseClicked
    
    private void BotonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAMouseClicked
        if (BotonA.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('A');
            jugar();
            BotonA.setEnabled(false);
        } else if (BotonA.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('A');
            jugar();
            BotonA.setEnabled(false);
        }
    }//GEN-LAST:event_BotonAMouseClicked

    private void BotonBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBMouseClicked
        if (BotonB.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('B');
            jugar();
            BotonB.setEnabled(false);
        } else if (BotonB.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('B');
            jugar();
            BotonB.setEnabled(false);
        }
    }//GEN-LAST:event_BotonBMouseClicked

    private void BotonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCMouseClicked
        if (BotonC.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('C');
            jugar();
            BotonC.setEnabled(false);
        } else if (BotonC.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('C');
            jugar();
            BotonC.setEnabled(false);
        }
    }//GEN-LAST:event_BotonCMouseClicked

    private void BotonDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDMouseClicked
        if (BotonD.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('D');
            jugar();
            BotonD.setEnabled(false);
        } else if (BotonD.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('D');
            jugar();
            BotonD.setEnabled(false);
        }           
    }//GEN-LAST:event_BotonDMouseClicked

    private void BotonEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEMouseClicked
        if (BotonE.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('E');
            jugar();
            BotonE.setEnabled(false);
        } else if (BotonE.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('E');
            jugar();
            BotonE.setEnabled(false);
        }
    }//GEN-LAST:event_BotonEMouseClicked

    private void BotonFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFMouseClicked
        if (BotonF.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('F');
            jugar();
            BotonF.setEnabled(false);
        } else if (BotonF.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('F');
            jugar();
            BotonF.setEnabled(false);
        }
    }//GEN-LAST:event_BotonFMouseClicked

    private void BotonGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGMouseClicked
        if (BotonG.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('G');
            jugar();
            BotonG.setEnabled(false);
        } else if (BotonG.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('G');
            jugar();
            BotonG.setEnabled(false);
        }
    }//GEN-LAST:event_BotonGMouseClicked

    private void BotonHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHMouseClicked
        if (BotonH.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('H');
            jugar();
            BotonH.setEnabled(false);
        } else if (BotonH.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('H');
            jugar();
            BotonH.setEnabled(false);
        }
    }//GEN-LAST:event_BotonHMouseClicked

    private void BotonIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIMouseClicked
        if (BotonI.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('I');
            jugar();
            BotonI.setEnabled(false);
        } else if (BotonI.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('I');
            jugar();
            BotonI.setEnabled(false);
        }
    }//GEN-LAST:event_BotonIMouseClicked

    private void BotonJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonJMouseClicked
        if (BotonJ.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('J');
            jugar();
            BotonJ.setEnabled(false);
        } else if (BotonJ.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('J');
            jugar();
            BotonJ.setEnabled(false);
        }
    }//GEN-LAST:event_BotonJMouseClicked

    private void BotonKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonKMouseClicked
        if (BotonK.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('K');
            jugar();
            BotonK.setEnabled(false);
        } else if (BotonK.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('K');
            jugar();
            BotonK.setEnabled(false);
        }
    }//GEN-LAST:event_BotonKMouseClicked

    private void BotonLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLMouseClicked
        if (BotonL.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('L');
            jugar();
            BotonL.setEnabled(false);
        } else if (BotonL.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('L');
            jugar();
            BotonL.setEnabled(false);
        }
    }//GEN-LAST:event_BotonLMouseClicked

    private void BotonMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMMouseClicked
        if (BotonM.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('M');
            jugar();
            BotonM.setEnabled(false);
        } else if (BotonM.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('M');
            jugar();
            BotonM.setEnabled(false);
        }
    }//GEN-LAST:event_BotonMMouseClicked

    private void BotonNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNMouseClicked
        if (BotonN.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('N');
            jugar();
            BotonN.setEnabled(false);
        } else if (BotonN.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('N');
            jugar();
            BotonN.setEnabled(false);
        }
    }//GEN-LAST:event_BotonNMouseClicked

    private void BotonÑMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonÑMouseClicked
        if (BotonÑ.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('Ñ');
            jugar();
            BotonÑ.setEnabled(false);
        } else if (BotonÑ.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('Ñ');
            jugar();
            BotonÑ.setEnabled(false);
        }
    }//GEN-LAST:event_BotonÑMouseClicked

    private void BotonOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOMouseClicked
        if (BotonO.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('O');
            jugar();
            BotonO.setEnabled(false);
        } else if (BotonO.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('O');
            jugar();
            BotonO.setEnabled(false);
        }
    }//GEN-LAST:event_BotonOMouseClicked

    private void BotonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMouseClicked
        if (BotonP.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('P');
            jugar();
            BotonP.setEnabled(false);
        } else if (BotonP.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('P');
            jugar();
            BotonP.setEnabled(false);
        }
    }//GEN-LAST:event_BotonPMouseClicked

    private void BotonQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonQMouseClicked
        if (BotonQ.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('Q');
            jugar();
            BotonQ.setEnabled(false);
        } else if (BotonQ.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('Q');
            jugar();
            BotonQ.setEnabled(false);
        }
    }//GEN-LAST:event_BotonQMouseClicked

    private void BotonRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRMouseClicked
        if (BotonR.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('R');
            jugar();
            BotonR.setEnabled(false);
        } else if (BotonR.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('R');
            jugar();
            BotonR.setEnabled(false);
        }
    }//GEN-LAST:event_BotonRMouseClicked

    private void BotonSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSMouseClicked
        if (BotonS.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('S');
            jugar();
            BotonS.setEnabled(false);
        } else if (BotonS.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('S');
            jugar();
            BotonS.setEnabled(false);
        }
    }//GEN-LAST:event_BotonSMouseClicked

    private void BotonTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTMouseClicked
        if (BotonT.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('T');
            jugar();
            BotonT.setEnabled(false);
        } else if (BotonT.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('T');
            jugar();
            BotonT.setEnabled(false);
        }
    }//GEN-LAST:event_BotonTMouseClicked

    private void BotonUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonUMouseClicked
        if (BotonU.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('U');
            jugar();
            BotonU.setEnabled(false);
        } else if (BotonU.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('U');
            jugar();
            BotonU.setEnabled(false);
        }
    }//GEN-LAST:event_BotonUMouseClicked

    private void BotonVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVMouseClicked
        if (BotonV.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('V');
            jugar();
            BotonV.setEnabled(false);
        } else if (BotonV.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('V');
            jugar();
            BotonV.setEnabled(false);
        }
    }//GEN-LAST:event_BotonVMouseClicked

    private void BotonWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonWMouseClicked
        if (BotonW.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('W');
            jugar();
            BotonW.setEnabled(false);
        } else if (BotonW.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('W');
            jugar();
            BotonW.setEnabled(false);
        }
    }//GEN-LAST:event_BotonWMouseClicked

    private void BotonXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonXMouseClicked
        if (BotonX.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('X');
            jugar();
            BotonX.setEnabled(false);
        } else if (BotonX.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('X');
            jugar();
            BotonX.setEnabled(false);
        }
    }//GEN-LAST:event_BotonXMouseClicked

    private void BotonYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonYMouseClicked
        if (BotonY.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('Y');
            jugar();
            BotonY.setEnabled(false);
        } else if (BotonY.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('Y');
            jugar();
            BotonY.setEnabled(false);
        }
    }//GEN-LAST:event_BotonYMouseClicked

    private void BotonZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonZMouseClicked
        if (BotonZ.isEnabled() && Main.adminPalabrasSecretas.isModoFijo()) {
            juegoAhorcadoFijo.setLetra('Z');
            jugar();
            BotonZ.setEnabled(false);
        } else if (BotonZ.isEnabled() && Main.adminPalabrasSecretas.isModoAzar()) {
            juegoAhorcadoAzar.setLetra('Z');
            jugar();
            BotonZ.setEnabled(false);
        }
    }//GEN-LAST:event_BotonZMouseClicked

    private void actualizarIntentos() {
        if (Main.adminPalabrasSecretas.isModoFijo() && !Main.adminPalabrasSecretas.isModoAzar()) {   
            if (juegoAhorcadoFijo.getIntentos() == 5) {
                Intento5.setVisible(true);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoFijo.getIntentos() == 4) {
                Intento5.setVisible(false);
                Intento4.setVisible(true);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoFijo.getIntentos() == 3) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(true);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoFijo.getIntentos() == 2) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(true);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoFijo.getIntentos() == 1) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(true);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoFijo.getIntentos() == 0) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(true);
                Main.adminPalabrasSecretas.setModoFijo(false);
                Main.adminPalabrasSecretas.setModoAzar(false);
                juegoAhorcadoFijo.setPartidaGanada(false);
                MenuPrincipal menuPrincipal = new MenuPrincipal();
                menuPrincipal.setVisible(true);
                this.setVisible(false);
            }
        } else if (Main.adminPalabrasSecretas.isModoAzar() && !Main.adminPalabrasSecretas.isModoFijo()) {
            if (juegoAhorcadoAzar.getIntentos() == 5) {
                Intento5.setVisible(true);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoAzar.getIntentos() == 4) {
                Intento5.setVisible(false);
                Intento4.setVisible(true);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoAzar.getIntentos() == 3) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(true);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoAzar.getIntentos() == 2) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(true);
                Intento1.setVisible(false);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoAzar.getIntentos() == 1) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(true);
                Intento0.setVisible(false);
            } else if (juegoAhorcadoAzar.getIntentos() == 0) {
                Intento5.setVisible(false);
                Intento4.setVisible(false);
                Intento3.setVisible(false);
                Intento2.setVisible(false);
                Intento1.setVisible(false);
                Intento0.setVisible(true);
                Main.adminPalabrasSecretas.setModoFijo(false);
                Main.adminPalabrasSecretas.setModoAzar(false);
                juegoAhorcadoAzar.setPartidaGanada(false);
                MenuPrincipal menuPrincipal = new MenuPrincipal();
                menuPrincipal.setVisible(true);
                this.setVisible(false);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AhorcadosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AhorcadosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AhorcadosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AhorcadosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhorcadosVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonA;
    private javax.swing.JButton BotonB;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonD;
    private javax.swing.JButton BotonE;
    private javax.swing.JButton BotonF;
    private javax.swing.JButton BotonG;
    private javax.swing.JButton BotonH;
    private javax.swing.JButton BotonI;
    private javax.swing.JButton BotonJ;
    private javax.swing.JButton BotonK;
    private javax.swing.JButton BotonL;
    private javax.swing.JButton BotonM;
    private javax.swing.JButton BotonN;
    private javax.swing.JButton BotonO;
    private javax.swing.JButton BotonP;
    private javax.swing.JButton BotonQ;
    private javax.swing.JButton BotonR;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JButton BotonS;
    private javax.swing.JButton BotonT;
    private javax.swing.JButton BotonU;
    private javax.swing.JButton BotonV;
    private javax.swing.JButton BotonW;
    private javax.swing.JButton BotonX;
    private javax.swing.JButton BotonY;
    private javax.swing.JButton BotonZ;
    private javax.swing.JPanel BotonesPanel;
    private javax.swing.JButton BotonÑ;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Intento0;
    private javax.swing.JLabel Intento1;
    private javax.swing.JLabel Intento2;
    private javax.swing.JLabel Intento3;
    private javax.swing.JLabel Intento4;
    private javax.swing.JLabel Intento5;
    private javax.swing.JLabel IntentosLabel;
    private javax.swing.JLabel PalabraOcultaLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
