/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahorcado;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class ModoJuego extends javax.swing.JFrame {

    public ModoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonRegresar = new javax.swing.JLabel();
        ModoJuegoInfo = new javax.swing.JLabel();
        BotonModoAzar = new javax.swing.JLabel();
        BotonModoFijo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 50, 50));

        ModoJuegoInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModoJuegoInfoMouseClicked(evt);
            }
        });
        jPanel1.add(ModoJuegoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 50, 40));

        BotonModoAzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModoAzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModoAzarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonModoAzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 250, 60));

        BotonModoFijo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModoFijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModoFijoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonModoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 250, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/ModoJuego.png"))); // NOI18N
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 727, 682));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        Main.adminPalabrasSecretas.setModoFijo(false);
        Main.adminPalabrasSecretas.setModoAzar(false);
        
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void ModoJuegoInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModoJuegoInfoMouseClicked
        InformacionModoJuego informacionModoJuego = new InformacionModoJuego();
        informacionModoJuego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModoJuegoInfoMouseClicked

    private void BotonModoFijoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModoFijoMouseClicked
        String palabra = JOptionPane.showInputDialog("Escriba su palabra secreta: ");
        
        if(palabra != null) {
            Main.adminPalabrasSecretas.setModoFijo(true);
            Main.adminPalabrasSecretas.setPalabraFija(palabra);
            AhorcadosVisual ahorcadosVisual = new AhorcadosVisual();
            ahorcadosVisual.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonModoFijoMouseClicked

    private void BotonModoAzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModoAzarMouseClicked
        Main.adminPalabrasSecretas.setModoAzar(true);
        AhorcadosVisual ahorcadosVisual = new AhorcadosVisual();
        ahorcadosVisual.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_BotonModoAzarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonModoAzar;
    private javax.swing.JLabel BotonModoFijo;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel ModoJuegoInfo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
